//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeremyTCD.DotNet.CommandLine.Tests {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DummyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DummyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JeremyTCD.DotNet.CommandLine.Tests.DummyStrings", typeof(DummyStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy description.
        /// </summary>
        internal static string CommandDescription_Dummy {
            get {
                return ResourceManager.GetString("CommandDescription_Dummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dummy.
        /// </summary>
        internal static string CommandName_Dummy {
            get {
                return ResourceManager.GetString("CommandName_Dummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DummyValue.
        /// </summary>
        internal static string DummyString {
            get {
                return ResourceManager.GetString("DummyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy description.
        /// </summary>
        internal static string OptionDescription_Dummy {
            get {
                return ResourceManager.GetString("OptionDescription_Dummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dummy.
        /// </summary>
        internal static string OptionLongName_Dummy {
            get {
                return ResourceManager.GetString("OptionLongName_Dummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiplevalues.
        /// </summary>
        internal static string OptionLongName_MultipleValues {
            get {
                return ResourceManager.GetString("OptionLongName_MultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to novalue.
        /// </summary>
        internal static string OptionLongName_NoValue {
            get {
                return ResourceManager.GetString("OptionLongName_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to singlevalue.
        /// </summary>
        internal static string OptionLongName_SingleValue {
            get {
                return ResourceManager.GetString("OptionLongName_SingleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string OptionShortName_Dummy {
            get {
                return ResourceManager.GetString("OptionShortName_Dummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mv.
        /// </summary>
        internal static string OptionShortName_MultipleValues {
            get {
                return ResourceManager.GetString("OptionShortName_MultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nv.
        /// </summary>
        internal static string OptionShortName_NoValue {
            get {
                return ResourceManager.GetString("OptionShortName_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sv.
        /// </summary>
        internal static string OptionShortName_SingleValue {
            get {
                return ResourceManager.GetString("OptionShortName_SingleValue", resourceCulture);
            }
        }
    }
}
