//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeremyTCD.DotNet.CommandLine {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JeremyTCD.DotNet.CommandLine.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;{0}&quot; does not exist.
        /// </summary>
        public static string Exception_CommandDoesNotExist {
            get {
                return ResourceManager.GetString("Exception_CommandDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands must have names.
        /// </summary>
        public static string Exception_CommandsMustHaveNames {
            get {
                return ResourceManager.GetString("Exception_CommandsMustHaveNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default command required.
        /// </summary>
        public static string Exception_DefaultCommandRequired {
            get {
                return ResourceManager.GetString("Exception_DefaultCommandRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple commands have the name &quot;{0}&quot;.
        /// </summary>
        public static string Exception_MultipleCommandsWithSameName {
            get {
                return ResourceManager.GetString("Exception_MultipleCommandsWithSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple default commands:
        ///{0}.
        /// </summary>
        public static string Exception_MultipleDefaultCommands {
            get {
                return ResourceManager.GetString("Exception_MultipleDefaultCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptionAttribute for property &quot;{0}&quot; must have either a short or long name..
        /// </summary>
        public static string Exception_OptionAttributeMustHaveName {
            get {
                return ResourceManager.GetString("Exception_OptionAttributeMustHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;{0}&quot; does not exist.
        /// </summary>
        public static string ParseException_CommandDoesNotExist {
            get {
                return ResourceManager.GetString("ParseException_CommandDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments.
        /// </summary>
        public static string ParseException_InvalidArguments {
            get {
                return ResourceManager.GetString("ParseException_InvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is an invalid value for option &quot;-{1}&quot;.
        /// </summary>
        public static string ParseException_InvalidOptionValue {
            get {
                return ResourceManager.GetString("ParseException_InvalidOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed arguments &quot;{0}&quot;.
        /// </summary>
        public static string ParseException_MalformedArguments {
            get {
                return ResourceManager.GetString("ParseException_MalformedArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default command.
        /// </summary>
        public static string ParseException_NoDefaultCommand {
            get {
                return ResourceManager.GetString("ParseException_NoDefaultCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &quot;-{0}&quot; does not exist.
        /// </summary>
        public static string ParseException_OptionDoesNotExist {
            get {
                return ResourceManager.GetString("ParseException_OptionDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run &quot;{0} -help&quot; for usage information..
        /// </summary>
        public static string Printer_AppGetHelpHint {
            get {
                return ResourceManager.GetString("Printer_AppGetHelpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run &quot;{0} {1} -help&quot; for usage information..
        /// </summary>
        public static string Printer_CommandGetHelpHint {
            get {
                return ResourceManager.GetString("Printer_CommandGetHelpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: {0}.
        /// </summary>
        public static string Printer_Description {
            get {
                return ResourceManager.GetString("Printer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run &apos;{0} {1}-help&apos; for more information about {2}..
        /// </summary>
        public static string Printer_GetHelpTip {
            get {
                return ResourceManager.GetString("Printer_GetHelpTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///{1}
        ///.
        /// </summary>
        public static string Printer_Header {
            get {
                return ResourceManager.GetString("Printer_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string Printer_ParseException {
            get {
                return ResourceManager.GetString("Printer_ParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: &apos;{0} {1}{2}&apos;.
        /// </summary>
        public static string Printer_Usage {
            get {
                return ResourceManager.GetString("Printer_Usage", resourceCulture);
            }
        }
    }
}
